// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/62eedc3121a5e28c50473d2e4a9cefbcb9c3957f/cordova-ionic/cordova-ionic.d.ts
interface CordovaPlugins {
  Keyboard:Ionic.Keyboard;
}